name: Deploy Static Web App

on:
  push:
    branches:
      - main # Replace 'main' with the branch you use for deployment

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"               # Path to your HTML/CSS files
          output_location: ""             # No output directory since it's static
          skip_app_build: true            # Skips the build process
